# Generated by Django 4.1.4 on 2024-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='homepage_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
