# Generated by Django 4.1.4 on 2024-06-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_profile_bio_link_alter_profile_homepage_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_link',
            new_name='Profile_bio',
        ),
    ]
