# Generated by Django 4.1.4 on 2024-06-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_rename_bio_link_profile_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_bio',
            new_name='profile_bio',
        ),
    ]
