name: Python Django Application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Ir para a subpasta onde o projeto está localizado (se estiver dentro de 'twitter_clone')
    - name: Navigate to subdirectory
      run: cd twitter_clone

    # Instalar poetry e dependências
    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
      working-directory: twitter_clone

    # Verificar a instalação do poetry
    - name: View poetry --help
      run: poetry --help
      working-directory: twitter_clone

    # Instalar as dependências do projeto
    - name: Install dependencies
      run: poetry install
      working-directory: twitter_clone

    # Rodar as migrações do banco de dados SQLite
    - name: Run migrations
      run: poetry run python manage.py migrate
      working-directory: twitter_clone

    # Rodar os testes Django
    - name: Test
      run: poetry run python manage.py test
      working-directory: twitter_clone

