name: Python Django Application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
    # Faz checkout do código no repositório (versão atualizada)
    - uses: actions/checkout@v3

    # Configura a versão do Python (versão atualizada)
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Instala o Poetry e as dependências do sistema
    - name: Install poetry and dependencies
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry
      working-directory: twitter_clone

    # Instala as dependências do projeto com poetry
    - name: Install project dependencies
      run: poetry install
      working-directory: twitter_clone

    # Executa as migrações no banco de dados SQLite
    - name: Run migrations
      run: poetry run python manage.py migrate
      working-directory: twitter_clone

    # Executa os testes do Django
    - name: Run tests
      run: poetry run python manage.py test
      working-directory: twitter_clone
